server:
  port: 8086
  servlet:
    session:
      timeout: PT1H   #1小时过期
spring:
  application:
    name: adopt
  resources:
    static-locations: classpath:/templates/,classpath:/static/

    #redis配置
    # 环境 dev|test|prod
  redis:
    database: 0           # Redis服务器数据库
    host: 127.0.0.1       # Redis服务器地址
    port: 6379            # Redis服务器连接端口
    password:             # Redis服务器连接密码（默认为空）
    timeout: 3000ms          # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 50   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mypet?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: 111

  thymeleaf:
    cache: false
    suffix: .html
    encoding: utf-8
    prefix: classpath:/templates/     # 访问template下的html文件需要配置模板


#mybatisplus===================================================
#逻辑删除
#mybatis-plus:
#  global-config:
#    db-config:
#      logic-delete-value: 1         #已删除
#      logic-not-delete-value: 0     #未删除    默认
#mybatis日志
mybatis-plus:
  type-aliases-package: com.wes.entry                     # 实体类所在包
  mapper-locations: classthpath*:/mapper/**Mapper.xml    #xml文件所在位置
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true #设置返回字段不为空，前端不报错





